version: "3"
services:
    db:
        image: postgres
        restart: always
        ports:
            - 5432:5432
        environment:
            - POSTGRES_USER=root
            - POSTGRES_PASSWORD=root
            - POSTGRES_DB=nojest
        volumes:
            - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql

    admin:
        image: adminer
        restart: always
        depends_on: 
            - db
        ports:
            - 8080:8080

    # pgadmin:
    #     container_name: pgadmin4_container
    #     image: dpage/pgadmin4
    #     restart: always
    #     environment:
    #         PGADMIN_DEFAULT_EMAIL: admin@admin.com
    #         PGADMIN_DEFAULT_PASSWORD: root
    #         PGADMIN_LISTEN_PORT: 80
    #     ports:
    #         - "8080:80"


    # app:
    #     build:
    #         context: ./
    #         target: dev
    #     command: npm start
    #     depends_on:
    #         - db
    #     ports:
    #         - 8000:8000
    #     volumes:
    #         - ./:/usr/src/app/
    #         - /usr/src/app/node_modules
    #     environment:
    #         DATABASE_URL: postgres://root:root@db:5432/nojest
    #         PORT: 8000
